### ISSUE TITLE
Static build failing with missing rdkafka-static.pc

### ISSUE THREAD

**Issue by mgilbir** [confluentinc/confluent-kafka-go#316]
Description
===========
When running `go build -tags static .` I get:
```
# pkg-config --cflags  -- rdkafka-static
Package rdkafka-static was not found in the pkg-config search path.
Perhaps you should add the directory containing `rdkafka-static.pc'
to the PKG_CONFIG_PATH environment variable
No package 'rdkafka-static' found
pkg-config: exit status 1
```

I've seen in [a comment](https://github.com/confluentinc/confluent-kafka-go/pull/250#discussion_r236589485) by @edenhill that rdkakfa-static was added in 0.11.4 and that using 0.11.6 should work, but I'm using the latest confluence debian package and it's not there.

Any ideas on what's happening?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 
* `github.com/confluentinc/confluent-kafka-go v0.11.6`
* `librdkafka++1 is already the newest version (0.11.6~1confluent5.1.2-1).`
* `librdkafka-dev is already the newest version (0.11.6~1confluent5.1.2-1).`
* ` librdkafka1 is already the newest version (0.11.6~1confluent5.1.2-1).`

 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [X] Operating system: `docker container golang:1.12.1-stretch`
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please try upgrading to librdkafka v1.0.0 by using the Confluent Platform 5.2 APT repo:
https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install

**Comment by danielkza** [comment]
`librdkafka-1.0.0~1confluent5.2.1-1` also does not provide `rdkafka-static.pc` anywhere after installing in Ubuntu 16.04.

**Comment by danielkza** [comment]
It also seems there is a temporary path left into `rdkafka.pc` that obviously will not work when installed elsewhere:

    Libs.private: -lm /tmp/confluent/build-area/librdkafka-1.0.0~1confluent5.2.1/mklove/deps/dest/zstd/usr/lib/x86_64-linux-gnu/libzstd.a -lsasl2 -lssl -lcrypto   -lcrypto   -lz   -ldl -lpthread -lrt

**Comment by jasongerard** [comment]
Running into same problem.

**Comment by lepek** [comment]
Same issue here, any plan to fix this?

**Comment by edenhill** [comment]
We're looking into providing a prebuilt librdkafka with the Go client.
You can give it a shot by changing your import from `../confluent-kafka-go/kafka..` to `../confluent-kafka-go-dev/kafka..`.
We'd be very interested to get your feedback on that solution.

Example usage:
https://github.com/confluentinc/confluent-kafka-go-example

**Comment by lepek** [comment]
I tested it in Centos 7 without librdkafka-devel or librdkafka installed and it worked out of the box with just the dependency change. Nice job! this will simplify so much the deployments. I will test it in Centos 6 shortly.

**Comment by edenhill** [comment]
@lepek That's great, thanks! We're looking to merge this into the proper repo in august.

**Comment by lepek** [comment]
Trying to build it in Centos6 I run into this error:
```
# github.com/confluentinc/confluent-kafka-go-dev/kafka
/root/go/pkg/mod/github.com/confluentinc/confluent-kafka-go-dev@v0.0.0-20190703144503-78a815343f20/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_queue.o): In function `rd_kafka_q_pop_serve':
(.text+0xb16): undefined reference to `timespec_get'
/root/go/pkg/mod/github.com/confluentinc/confluent-kafka-go-dev@v0.0.0-20190703144503-78a815343f20/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_queue.o): In function `rd_kafka_q_serve':
(.text+0xe29): undefined reference to `timespec_get'
/root/go/pkg/mod/github.com/confluentinc/confluent-kafka-go-dev@v0.0.0-20190703144503-78a815343f20/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_queue.o): In function `rd_kafka_q_serve_rkmessages':
(.text+0x161e): undefined reference to `timespec_get'
/root/go/pkg/mod/github.com/confluentinc/confluent-kafka-go-dev@v0.0.0-20190703144503-78a815343f20/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka.o): In function `rd_kafka_new':
(.text+0x2217): undefined reference to `timespec_get'
/root/go/pkg/mod/github.com/confluentinc/confluent-kafka-go-dev@v0.0.0-20190703144503-78a815343f20/kafka/librdkafka/librdkafka_glibc_linux.a(getenv.o): In function `ossl_safe_getenv':
(.text+0x1): undefined reference to `secure_getenv'
collect2: ld returned 1 exit status
```

**Comment by edenhill** [comment]
@lepek What version of centos and glibc?

**Comment by Knight-Wu** [comment]
@edenhill  hi, i am encountered the same problem :
# pkg-config --cflags  -- rdkafka-static
Package rdkafka-static was not found in the pkg-config search path.
Perhaps you should add the directory containing `rdkafka-static.pc'
to the PKG_CONFIG_PATH environment variable
No package 'rdkafka-static' found
pkg-config: exit status 1
, so i try confluent-kafka-go-dev, it finally worked, why not release it ? Is this version stable , and can be used in production ?

**Comment by edenhill** [comment]
We're collecting community feedback and planning to release bundled builds during Q3

**Comment by lepek** [comment]
I know this is closed, but following up my last error, once I upgraded to glib 2.17 it worked. It didn't worked with glib 2.12
