### ISSUE TITLE
1.4.0: Building apps fails on latest alpine, when using bundled librdkafka

### ISSUE THREAD

**Issue by bschofield** [confluentinc/confluent-kafka-go#454]
Description
===========

When using the 1.4.0 release, the bundled _librdkafka_ fails to work as intended with the latest alpine.

How to reproduce
================

Build an application which uses _github.com/confluentinc/confluent-kafka-go_, in a container, using the alpine:3.11 image (which, at the time of writing, is actually alpine:3.11.5) as a base. Errors such as the following will be displayed:

```
 go: downloading github.com/confluentinc/confluent-kafka-go v1.4.0
 # github.com/confluentinc/confluent-kafka-go/kafka
 /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.4.0/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_txnmgr.o): in function `rd_kafka_txn_set_fatal_error':
 (.text+0x141): undefined reference to `__strdup'
 /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.4.0/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_txnmgr.o): in function `rd_kafka_txn_set_abortable_error':
 (.text+0x64f): undefined reference to `__strdup'
...
```

Installing a fresh build of _librdkafka_ 1.4.0 into the container and building the application with `-tags dynamic`  resolves the issue.

Could possibly be because the bundled _librdkafka_ was built from a :edge release of alpine, instead of :latest?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.4.0, bundled.
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: N/A
 - [x] Operating system: Alpine Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary): N/A
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue: No

**Comment by otavioprado** [comment]
same issue here

**Comment by edenhill** [comment]
Thank you for reporting this.

The bundled librdkafka alpine builds is built on Alpine 3.8.

**Comment by edenhill** [comment]
@bschofield 
Did you build your application with `-tags musl`? It seems like it is linking the glibc librdkafka (which references __strdup).

**Comment by edenhill** [comment]
@otavioprado Since you are on Debian you should not see the link error, can you provide the full output (including build command) that fails your Go application build?

**Comment by bschofield** [comment]
@edenhill Thanks for the fast response!

I did not use `-tags musl`. Using `-tags musl` does indeed fix the issue.

Would it be useful to include a comment about the need to add `-tags musl` for alpine builds, in https://github.com/confluentinc/confluent-kafka-go/blob/master/README.md#install-the-client? At the moment I see that you do mention it in a separate repo (https://github.com/confluentinc/confluent-kafka-go-example/blob/master/README.md), but you don't mention it in the main repo README.

**Comment by blaketastic2** [comment]
Along these same lines, I can confirm that this worked with `golang:1.13.10-alpine3.10` as my builder_base image with librdkafka v1.3.0.

```Dockerfile
...
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -tags static_all,netgo -o /bin/app ./cmd/**/main.go

# final stage
FROM alpine:3.10
COPY --from=builder_base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder_base /bin/app /bin/app
```

But as soon as I switch to 1.4.0 of confluent-kafka-go, and librdkafka, I get the below error:
```
BROKERFAIL|rdkafka#consumer-1| [thrd:sasl_ssl://cloud_host:9092/bootstr]: sasl_ssl://cloud_host:9092/bootstrap: failed: err: Local: SSL error: (errno: No error information)
```

Here's the base image with the updated versions... For the working version, just substitute the docker image to `golang:1.13.10-apine3.11`, librdkafka `v1.3.0`.

**Comment by fals** [comment]
@blaketastic2 I'm trying to build with yours, and I'm getting multiple errors:

`undefined reference to `__strdup'`

**Comment by blaketastic2** [comment]
Yea, I’m not able to get 1.4.0 to build. I have it working for 1.3.0 and that can be seen here https://github.com/confluentinc/confluent-kafka-go/issues/461

**Comment by bschofield** [comment]
@blaketastic2 @fals Set `-tags musl` if you want to use the built-in librdkafka, set `-tags dynamic` if you want to use your own librdkafka. Closing this now as it wasn't a bug.

**Comment by blaketastic2** [comment]
@bschofield Building with `-tags musl` and removing `-tags static_all` still results in the same broker fail message, but it does build. I'll track the brokerfail on another issue.
```
BROKERFAIL|rdkafka#consumer-1| [thrd:sasl_ssl://cloud_host:9092/bootstr]: sasl_ssl://cloud_host:9092/bootstrap: failed: err: Local: SSL error: (errno: No error information)
```

**Comment by bschofield** [comment]
@blaketastic2 Your broker fail message sounds like it's caused by the included librdkafka not having the SSL support you need. Try compiling your own librdkafka (1.4.0) and then building the go app with `-tags static` -- this is what I was doing in production and it was working for me, with SSL enabled.

**Comment by blaketastic2** [comment]
I ended up getting past this by continuing to copy the ca-certificates into the docker image as I mentioned earlier, and then making sure the consumer set:

`ssl.ca.location=/etc/ssl/certs/ca-certificates.crt`

Setting this prior to 1.4.0 was not needed, and instead was able to find the ssl ca on its own.

**Comment by lifeofguenter** [comment]
I am getting:

```
./xxx.go:15:9: undefined: kafka.Producer
```

when building:

```
FROM golang:1.14-alpine AS builder

WORKDIR /go/src/app
COPY . .
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux go build -a -v -tags musl
```

**Comment by lifeofguenter** [comment]
Ok seems like this works:

```
# builder
FROM golang:1.14-alpine AS builder

RUN set -ex &&\
    apk add --no-progress --no-cache \
      gcc \
      musl-dev

WORKDIR /go/src/app
COPY go.* ./
RUN go mod download

COPY . .
RUN go get -d -v
RUN GOOS=linux GOARCH=amd64 go build -a -v -tags musl
```

e.g. I think the key points:

* removing the `CGO_ENABLED` flag
* adding build tools into the build stage

**Comment by sneko** [comment]
Hi,

Got this issue too, added the `-tags musl` to fix it. So thank you!

But a question, now my Jenkins builds take twice the previous build time... Anything that could explain that?

To be honest, due to that I'm wondering if I'm not gonna stay with embedding librd on my own 😭

**Comment by edenhill** [comment]
The `go get` download will take more time as the librdkafka blobs need to be downloaded, and static linking will be somewhat slower than dynamic, but not by much.

**Comment by sneko** [comment]
@edenhill I have 3 steps:
- install deps (takes 18 seconds)
- vendoring deps to be passed across build stages (takes 2 seconds)
- build (takes 3m53s)
- coverage (takes 4m10s seconds)
- test (takes 3m55s seconds)

Whereas previously before the Confluent update and `-tags musl` (with everything else the same) I had:
- install deps (takes 43 seconds)
- vendoring deps to be passed across build stages (takes 1 seconds)
- build (takes 1m38s)
- coverage (takes 1m23s)
- test (takes 1m09s)

The detailed commands are the following ones:
- install deps: `go mod tidy`
- vendoring deps: `go mod vendor`
- build: `go build -mod=vendor -i -tags musl -o build/main -ldflags main.go`
- coverage: `go test -mod=vendor -race -cover ./...`
- test: `go test -mod=vendor ./...`

The difference is quite significative 🤔

**Comment by edenhill** [comment]
That does seem odd, maybe you can pass -x to the build to get an idea what steps are taking longer with the static builds.

**Comment by sneko** [comment]
@edenhill , after multiple retries of building the same Git commit, I succeeded lowering `build/coverage/test` to `2m20s` approximatively.

So it could come from the build servers... A bit weird but better to consider this than a big change with embedded Kafka lib.

Thank you for answering 👍 ,

**Comment by ja8zyjits** [comment]
After following @lifeofguenter  I was able to build but not run the file.


```bash
FROM golang:1.14-alpine AS builder

RUN set -ex &&\
    apk add --no-progress --no-cache \
      gcc \
      musl-dev

# Set necessary environmet variables needed for our image

ENV GO111MODULE=on \
    # CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the application
RUN go get -d -v
RUN go build -a -tags musl -o main myproject.go

# Move to /dist directory as the place for resulting binary folder
WORKDIR /dist

# Copy binary from build to main folder
RUN cp /build/main .

# Build a small image
FROM scratch

COPY --from=builder /dist/main /

# Command to run
ENTRYPOINT ["/main"]
```
I get the following error on running the file.
```bash
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by ja8zyjits** [comment]
Fixed by creating a static link
```bash
RUN go build -a -tags musl -installsuffix cgo -ldflags '-extldflags "-static"'  -o main backupstore_arango.go
```

**Comment by bulletblp4** [comment]
So I get the error mentioned in the description while running tests for my project via jenkins. (not sure if this is related)
Dockerfile

```FROM golang:1.14-alpine AS test

WORKDIR /src
# Packages required for project build and test

RUN apk add --no-cache git make
RUN go get \
        github.com/AlekSi/gocov-xml \
        github.com/axw/gocov \
        github.com/tebeka/go2xunit \
        github.com/wadey/gocovmerge

COPY go.mod go.sum ./
RUN  go mod download

# This layer is rebuilt when a file changes in the project directory
COPY . .
FROM test AS builder
ENV CGO_ENABLED=1
RUN set -ex &&\
    apk add --no-progress --no-cache \
      gcc \
      musl-dev

WORKDIR /src
RUN go install -tags musl ./...
FROM alpine:3.12.0
COPY --from=builder /go/bin/push3 /bin/
USER nobody
ENTRYPOINT ["push3"]
```

Jenkins snippet

```
        stage("Test") {
            agent {
                dockerfile {
                    label 'docker'
                    additionalBuildArgs '--target test'
                    args '-v test:/src/test'
                    reuseNode true
                }
            }

            steps {
                //This is old parallel stages syntax. As of Declarative Pipeline 1.2 it changes
                //Declarative Pipeline 1.2 docs https://jenkins.io/blog/2017/09/25/declarative-1/
                parallel(
                        'Unit Test': {
                            sh "make ${makeArgs} test/unit-test"
                        },
                        Coverage: {
                            sh "make ${makeArgs} test/coverage"
                        },
                        Vet: {
                            sh "make ${makeArgs} test/vet"
                        }
                )
            }
            post {
                always {
                    junit 'test/*xml'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'test', reportFiles: 'coverage.html', reportName: 'Code Coverage Report'])
                    sh "make ${makeArgs} clean"
                }
            }
        }
```

**Comment by edenhill** [comment]
Can't reproduce with vanilla docker image:
```bash
$ docker run -it golang:1.14-alpine /bin/sh
Unable to find image 'golang:1.14-alpine' locally
1.14-alpine: Pulling from library/golang
df20fa9351a1: Already exists
ed8968b2872e: Already exists
a92cc7c5fd73: Already exists
f17c8f1adafb: Pull complete
03954754c53a: Pull complete
Digest: sha256:e9f6373299678506eaa6e632d5a8d7978209c430aa96c785e5edcb1eebf4885e
Status: Downloaded newer image for golang:1.14-alpine
/go # apk add gcc musl-dev make git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/18) Installing libgcc (9.3.0-r2)
(2/18) Installing libstdc++ (9.3.0-r2)
(3/18) Installing binutils (2.34-r1)
(4/18) Installing gmp (6.2.0-r0)
(5/18) Installing isl (0.18-r0)
(6/18) Installing libgomp (9.3.0-r2)
(7/18) Installing libatomic (9.3.0-r2)
(8/18) Installing libgphobos (9.3.0-r2)
(9/18) Installing mpfr4 (4.0.2-r4)
(10/18) Installing mpc1 (1.1.0-r1)
(11/18) Installing gcc (9.3.0-r2)
(12/18) Installing nghttp2-libs (1.41.0-r0)
(13/18) Installing libcurl (7.69.1-r0)
(14/18) Installing expat (2.2.9-r1)
(15/18) Installing pcre2 (10.35-r0)
(16/18) Installing git (2.26.2-r0)
(17/18) Installing make (4.3-r0)
(18/18) Installing musl-dev (1.1.24-r9)
Executing busybox-1.31.1-r16.trigger
OK: 157 MiB in 33 packages
/go # cd src/
/go/src # mkdir fo
/go/src # cd fo
/go/src/fo # cat > main.go
package main

import (
	"github.com/confluentinc/confluent-kafka-go/kafka"
	"fmt"
)



func main () {
	_, vs := kafka.LibraryVersion()
	fmt.Printf("Kafka version %s\n", vs)
}

/go/src/fo # go get -tags musl
/go/src/fo # go build -tags musl
/go/src/fo # ./fo
Kafka version 1.4.2
/go/src/fo # ldd fo
	/lib/ld-musl-x86_64.so.1 (0x7f4f65cb7000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f4f65cb7000)
/go/src/fo #
```

**Comment by bulletblp4** [comment]
So the build works. When I run tests on it is when I get the error. i.e on running `go test ./...` or  `go vet ./...`

**Comment by edenhill** [comment]
You might need `-tags musl` on those commands too.

**Comment by lenimartin** [comment]
I am facing the same issue, from the container I can run `go build -a -tags musl ` and it works fine, but `go test ./... -tags musl` fails just as as @bulletblp4 ...

what I am missing ?

**Comment by hijklmno** [comment]
I struggled with this, and didn't realize we need the `-tags musl` in the run statement as well. This was my final piece of the puzzle:
```
go run -tags musl .`
```
