### ISSUE TITLE
go get -tags static find unresolved sasl symbols

### ISSUE THREAD

**Issue by thehh1974** [confluentinc/confluent-kafka-go#93]
Description
===========
After upgrading librdkafka to 0.11.0 (which is now mandatory) I get the following:
go get -tags static github.com/confluentinc/confluent-kafka-go/kafka
github.com/confluentinc/confluent-kafka-go/kafka
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_close':
(.text+0x244): undefined reference to `sasl_dispose'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_recv':
(.text+0xda2): undefined reference to `sasl_client_step'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_recv':
(.text+0xdb6): undefined reference to `sasl_errdetail'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_recv':
(.text+0xf7b): undefined reference to `sasl_getprop'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_recv':
(.text+0xf9d): undefined reference to `sasl_getprop'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_recv':
(.text+0xfbf): undefined reference to `sasl_getprop'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_client_new':
(.text+0x1540): undefined reference to `sasl_client_new'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_client_new':
(.text+0x1591): undefined reference to `sasl_client_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_client_new':
(.text+0x160d): undefined reference to `sasl_errdetail'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_client_new':
(.text+0x1676): undefined reference to `sasl_listmech'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_client_new':
(.text+0x1717): undefined reference to `sasl_errstring'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_global_init':
(.text+0x1795): undefined reference to `sasl_client_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_global_init':
(.text+0x17af): undefined reference to `sasl_errstring'
collect2: error: ld returned 1 exit status

This is on Ubuntu 4.16 with libsasl2-dev installed.

How to reproduce
================
Run: go get -tags static github.com/confluentinc/confluent-kafka-go/kafka

**Comment by edenhill** [comment]
Can you run these two commands and paste the output here?
`pkg-config --libs rdkafka`
`pkg-config --libs --static rdkafka`

**Comment by thehh1974** [comment]
~$ pkg-config --libs rdkafka
-L/usr/local/lib -lrdkafka
~$ pkg-config --libs --static rdkafka
-L/usr/local/lib -lrdkafka -lpthread -lz -lcrypto -lssl -lrt -ldl

**Comment by thehh1974** [comment]
After deleting /usr/local/lib/pkgconfig/rdkafka* problem solved!

**Comment by edenhill** [comment]
@thehh1974 Interesting. Did you have two installations of librdkafka on your system?

**Comment by thehh1974** [comment]
I did. I built one from source. I removed the libs and headers but not the
.pc files.

**Comment by ilanoh** [comment]
@thehh1974 Hello, I didn't understood how you resolved this specific issue, I receive exactly the same

**Comment by thehh1974** [comment]
I had two installations of librdkafka on my machine. One installed with apt
and one built from source.
Once I removed the one I built, including headers, libs and most
importantly .pc files (In /usr/local/lib/pkgconfig/rdkafka*), the issue
went away.

Haim

**Comment by ilanoh** [comment]
I may have the same issue, I have rdkafka.pc rdkafka-static.pc rdkafka++.pc rdkafka++-static.pc, do you think it is linked ?
