### PR TITLE
Add -lssp to windows builds since zstd and zlib are built with stack protection

### LINKED ISSUE #965: Link edit errors after upgrade from v1.9.2 to v2.0.2
Description
===========
We're trying to upgrade to v2.0.2.  Developing microservices so to debug with telepresence, we need to compile and debug on  Windows 10.

Our client compiles and runs fine if it's built inside a linux container, but to debug with telepresence we have to compile our client in either windows or on a mac.  I'm on Windows and it all worked fine on v1.9.2 but with v2.0.2 in the IDE  I get these link edit errors:

C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.0.2/kafka/librdkafka_vendor/librdkafka_windows.a(trees.o):(.text+0x64e): undefined reference to `__stack_chk_fail'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.0.2/kafka/librdkafka_vendor/librdkafka_windows.a(trees.o):(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.0.2/kafka/librdkafka_vendor/librdkafka_windows.a(inflate.o):(.text+0x21a8): undefined reference to `__stack_chk_fail'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.0.2/kafka/librdkafka_vendor/librdkafka_windows.a(inflate.o):(.text+0x2754): undefined reference to `__stack_chk_fail'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.0.2/kafka/librdkafka_vendor/librdkafka_windows.a(inftrees.o):(.text+0x56b): undefined reference to `__stack_chk_fail'
collect2.exe: error: ld returned 1 exit status

Is this a known problem?  Is compiling on windows no longer supported as it was on v1.9.2?

How to reproduce
================

try to build kafka client project in intellij on windows 10.

Checklist
=========
Please provide the following information:

 - [ x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 2.0.2
 - [ x] Apache Kafka broker version:  does not matter since build is failing.
 - [ x] Client configuration: `ConfigMap{...}`  does not matter since build is failing.
 - [ x] Operating system: Windows 10 Enterprise
 - [ x] Provide client logs (with `"debug": ".."` as necessary)   does not matter since build is failing.
 - [ x] Provide broker log excerpts    does not matter since build is failing.
 - [ x] Critical issue  YES

### PR DESCRIPTION
**Pull request by milindl**
Fixes #965 
This error has been there since 2.0.0 onwards after the CI was changed.
The static librdkafka bundle includes libzstd and libz, both of which are built with -fstack-protector (they are obtained from MinGW, not built). 

Thus, linkage to libssp is needed to make cgo compilation work.

### CODE REVIEW

**Review by emasab — APPROVED** [review]
LGTM Thanks Milind

File: CHANGELOG.md [hunk 1]
```diff
@@ -1,10 +1,26 @@
...
 
+# v2.5.0
+
+This is a feature release.
+
+## Fixes
+
+ * Windows builds are linked to `libssp` in addition to other libraries, since
+   the bundled zstd and zlib are built with `-fstack-protector`, and not linking
+   causes build failures. (#1184).
```
Comment (emasab) [inline CHANGELOG.md:11]:
```suggestion
 * Issues: #965
   Windows builds are linked to `libssp` in addition to other libraries, since
   the bundled zstd and zlib are built with `-fstack-protector`, and not linking
   causes build failures.
   Happening since 2.0.0 (#1184).
```

**Review by emasab — APPROVED** [review]
