### ISSUE TITLE
After upgrading to 2.1.1, there are compilation errors in the Mac environment.

### ISSUE THREAD

**Issue by jiaoew1991** [confluentinc/confluent-kafka-go#1010]
Description
===========
We want to upgrade confluent-kafka-go to 2.1.1. However, we encountered the following error during compilation in the Mac environment. It seems that the version of openssl is not quite right. Do you have any suggestions?

```
/Users/runner/hostedtoolcache/go/1.18.10/x64/pkg/tool/darwin_amd64/link: running ccache failed: exit status 1
ld: warning: -no_pie is deprecated when targeting new OS versions
Undefined symbols for architecture x86_64:
  "_OPENSSL_ia32cap_P", referenced from:
      _init_info_strings_ossl_ in librdkafka_darwin_amd64.a(libcrypto-lib-info.o)
      _ossl_cipher_capable_aes_cbc_hmac_sha1 in librdkafka_darwin_amd64.a(libdefault-lib-cipher_aes_cbc_hmac_sha1_hw.o)
      _aesni_cbc_hmac_sha1_tls1_multiblock_aad in librdkafka_darwin_amd64.a(libdefault-lib-cipher_aes_cbc_hmac_sha1_hw.o)
      _ossl_cipher_capable_aes_cbc_hmac_sha256 in librdkafka_darwin_amd64.a(libdefault-lib-cipher_aes_cbc_hmac_sha256_hw.o)
      _aesni_cbc_hmac_sha256_cipher in librdkafka_darwin_amd64.a(libdefault-lib-cipher_aes_cbc_hmac_sha256_hw.o)
      _aesni_cbc_hmac_sha256_tls1_multiblock_aad in librdkafka_darwin_amd64.a(libdefault-lib-cipher_aes_cbc_hmac_sha256_hw.o)
      _ossl_prov_aes_hw_ccm in librdkafka_darwin_amd64.a(libdefault-lib-cipher_aes_ccm_hw.o)
      ...
ld: symbol(s) not found for architecture x86_64
```

How to reproduce
================

This issue can be reproduced using this PR.
https://github.com/milvus-io/milvus/pull/24709

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 2.1.1
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Mac
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [x] Critical issue
